### ISSUE TITLE
Typescript issue with 1.0.0-next.2

### ISSUE THREAD

**Issue by surrealroad** [konvajs/svelte-konva#222]
I may be totally misunderstanding how this should work, but I can't get typescript to work with 1.0.0-next.2.

For example:
```
	import { Stage, Layer, Image as KonvaImage } from 'svelte-konva';
	let list: Array<any> = $state([]);
	let nextId = 0;
	let stage: typeof Stage | undefined = $state();
	

<Stage {width} {height} draggable={true} onwheel={handleWheel} bind:this={stage}>
	<Layer>
		{#each list as item (item.id)}
			<KonvaImage
				x={item.x}
				y={item.y}
				image={item.image}
				rotation={item.rotation}
				id={item.id}
				bind:this={item.handle}
			/>
		{/each}
	</Layer>
</Stage>
```

Gives me typescript errors on both the use of e.g. `stage?.handle().batchDraw();` 
```
Property 'handle' does not exist on type 'Component<{ staticConfig?: boolean | undefined; } & KonvaEventHooks & { [x: string]: any; clearBeforeDraw?: boolean | undefined; clipFunc?: ((ctx: SceneContext) => ClipFuncOutput) | undefined; ... 27 more ...; filters?: Filter[] | undefined; } & PropsContainer & PropsStage, { ...; }, "x" | "y">'.ts(2339)
```

as well as on the `bind:this={stage}`
```
Type 'SvelteComponent<{ staticConfig?: boolean | undefined; } & KonvaEventHooks & { [x: string]: any; clearBeforeDraw?: boolean | undefined; clipFunc?: ((ctx: SceneContext) => ClipFuncOutput) | undefined; ... 27 more ...; filters?: Filter[] | undefined; } & PropsContainer & PropsStage, any, any> & { ...; } & { ...; }' is not assignable to type 'Component<{ staticConfig?: boolean | undefined; } & KonvaEventHooks & { [x: string]: any; clearBeforeDraw?: boolean | undefined; clipFunc?: ((ctx: SceneContext) => ClipFuncOutput) | undefined; ... 27 more ...; filters?: Filter[] | undefined; } & PropsContainer & PropsStage, { ...; }, "x" | "y"> | undefined'.
  Type 'SvelteComponent<{ staticConfig?: boolean | undefined; } & KonvaEventHooks & { [x: string]: any; clearBeforeDraw?: boolean | undefined; clipFunc?: ((ctx: SceneContext) => ClipFuncOutput) | undefined; ... 27 more ...; filters?: Filter[] | undefined; } & PropsContainer & PropsStage, any, any> & { ...; } & { ...; }' is not assignable to type 'Component<{ staticConfig?: boolean | undefined; } & KonvaEventHooks & { [x: string]: any; clearBeforeDraw?: boolean | undefined; clipFunc?: ((ctx: SceneContext) => ClipFuncOutput) | undefined; ... 27 more ...; filters?: Filter[] | undefined; } & PropsContainer & PropsStage, { ...; }, "x" | "y">'.
    Type 'SvelteComponent<{ staticConfig?: boolean | undefined; } & KonvaEventHooks & { [x: string]: any; clearBeforeDraw?: boolean | undefined; clipFunc?: ((ctx: SceneContext) => ClipFuncOutput) | undefined; ... 27 more ...; filters?: Filter[] | undefined; } & PropsContainer & PropsStage, any, any> & { ...; } & { ...; }' provides no match for the signature '(this: void, internals: Brand<"ComponentInternals">, props: { staticConfig?: boolean | undefined; } & KonvaEventHooks & { [x: string]: any; clearBeforeDraw?: boolean | undefined; ... 28 more ...; filters?: Filter[] | undefined; } & PropsContainer & PropsStage): { ...; } & { ...; }'.ts(2322)
```

**Comment by TeyKey1** [comment]
Hi @surrealroad

I think you're running into the Problem described in https://github.com/sveltejs/language-tools/issues/2522

One solution is to type `stage` as per the following comment's suggestion https://github.com/sveltejs/language-tools/issues/2522#issuecomment-2380048973 (This is the current way I type bind:this of svelte-konva components inside the [repository example Project](https://github.com/konvajs/svelte-konva/blob/dee898c5ff86d1ca2b048e74d5d537f3d9d98016/src/routes/examples/connectFour/Token.svelte#L24)).

```typescript
let stage: ReturnType<typeof Stage> | undefined = $state();
```

With [svelte-check v4.0.6](https://github.com/sveltejs/language-tools/releases/tag/svelte-check-4.0.6) there is now a convenience feature where the tool provides the type for you so you could type it the same as in svelte3/4:

```typescript
let stage: Stage | undefined = $state();
```

Hope this helps. Please let me know if this fixes the problems you face.

**Comment by surrealroad** [comment]
It does! Thanks so much
